# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('term', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('area', models.CharField(max_length=30)),
                ('seat', models.CharField(max_length=10)),
                ('zname', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='XiaoMai',
        ),
    ]
