# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_auto_20171113_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cron',
        ),
    ]
