# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cron',
            old_name='name',
            new_name='ctype',
        ),
        migrations.RenameField(
            model_name='cron',
            old_name='age',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='cron',
            name='zname',
        ),
    ]
